### PR TITLE
2.8.0

### LINKED ISSUE #178: New features in latest version don't work (sunglasses, aiming bug mods):
## Issue Summary:

The newest features in the 2.6.0 and hotfix do not work on my PC. I tested the sunglasses and the bug fix which prevents your gun from automatically aiming if you unequip it while aiming, however, they both did not work. Other mod features continue to work. I use a 4070 and 7900x. 

## MGSHDFix & Game Version Numbers:

v.2.6.0 & v2.6.1 and the MGS2 version is the very latest

## Log Files:

[MGSHDFix.log](https://github.com/user-attachments/files/21564252/MGSHDFix.log)

## Reproduction:

Setting Sunglasses to Always wear sunglasses, and Fix Aiming After Equip to true, do not make any difference, and the game behaves as it normally would.

### LINKED ISSUE #183: Game won't launch with mgshdfix installed
## Issue Summary:

Game doesn't launch with MGSHDFix installed.

## Log Files:

[MGSHDFix_Game.log](https://github.com/user-attachments/files/21700117/MGSHDFix_Game.log)
[MGSHDFix_Launcher.log](https://github.com/user-attachments/files/21700118/MGSHDFix_Launcher.log)
 
## Reproduction:

I can open the launcher but when I go to start the game the launcher closes and nothing happens. If I modify the mgshdfix config to skip the launcher the game doesn't start at all, nothing happens when I click start game. Uninstalling the mod fixes the issue. I can run other mods fine, but MGSHDFix stops the game from working - be it a modded game, or vanilla.

I tried 2.6.2 and 2.7.0, both are the same.

### LINKED ISSUE #186: Strange crash at the healing tutorial
## Issue Summary:

There is a strange bug I seem to encounter that I don't know is only specific to my hardware or not, but every time I complete the healing tutorial, it seems to crash right afterwards.  It also only happens when a controller is plugged in, and the only way to "fix" it (trust me I've tried everything) is to limit the core affinity to two.  When the crash happens also depends on how long you've played the game for, if you load a save at that point, it won't crash, but if you reload it again, it will crash and keep crashing.  And for any more information, here are the crash logs from Event Viewer.

Faulting application name: METAL GEAR SOLID3.exe, version: 2.0.1.0, time stamp: 0x673eea11
Faulting module name: METAL GEAR SOLID3.exe, version: 2.0.1.0, time stamp: 0x673eea11
Exception code: 0xc0000005
Fault offset: 0x000000000010e62f
Faulting process id: 0x4664
Faulting application start time: 0x1DC0EF6884BB7E8
Faulting application path: D:\SteamLibrary\steamapps\common\MGS3\METAL GEAR SOLID3.exe
Faulting module path: D:\SteamLibrary\steamapps\common\MGS3\METAL GEAR SOLID3.exe
Report Id: bcb0ab6e-abaa-473e-aecc-ce70fb5e63f8
Faulting package full name: 
Faulting package-relative application ID: 

## Log Files:

[MGSHDFix_Game.log](https://github.com/user-attachments/files/21820526/MGSHDFix_Game.log)

## Reproduction:

Get to the healing tutorial on the virtuous mission with a controller and complete it, the crash will happen, recommended a 9800X3D is used.

### PR DESCRIPTION
**Pull request by ShizCalev**
Fixes #178
Fixes #183
Closes #186
Closes #180

Fixes HD Collection era NVG crosshair bug in MGS3.
before (crosshairs are in the upper left)
rAQemtx

after:
2025-08-11_00-49-41-METAL_GEAR_SOLID3-METAL_GEAR_SOLID_3_SNAKE_EATER

### CODE REVIEW

File: src/fixes/aiming_after_equip.cpp [hunk 1]
```diff
@@ -14,9 +14,23 @@ void FixAimAfterEquip::Initialize()
...
+            }
+            });
+
+        MAKE_HOOK_MID(baseModule, "89 1D ?? ?? ?? ?? 8B C3 48 83 C4", "MGS2: Aiming After Equip - Location 2", {
             g_GameVars.SetAimingState(0);
-        })
+            });
+
+        MAKE_HOOK_MID(baseModule, "BB ?? ?? ?? ?? 66 89 81", "MGS2: test 2", {
+            spdlog::info("test 2");
```
Comment (ShizCalev) [inline src/fixes/aiming_after_equip.cpp]: .

File: src/fixes/mgs3_hud_fixes.cpp [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+        return;
+    }
+
+    MAKE_HOOK_MID(baseModule, "F3 0F 59 C7 F3 0F 2C C8 66 89 48 ?? 66 3B D1 74 ?? 81 48 ?? ?? ?? ?? ?? 0F B7 48", "MGS3: NVG Cross", {
+        ctx.xmm1.f32[0] += 160.0f; //y axis
+        ctx.xmm0.f32[0] = ((((ctx.xmm0.f32[0] - 256.0f) * 2) + 512.0f) - 32.0f); //x axis
+        });
+
+    MAKE_HOOK_MID(baseModule, "F3 0F 59 C7 F3 0F 2C C8 66 89 48 ?? 66 3B D1 74 ?? 81 48 ?? ?? ?? ?? ?? 0F B7 48", "MGS3: NVG Cross 2", {
+        spdlog::info("MGS3: NVG Cross 2 - Location 1");
```
Comment (ShizCalev) [inline src/fixes/mgs3_hud_fixes.cpp]: .

File: src/resources/logging.cpp [hunk 3]
```diff
@@ -107,11 +107,11 @@ void Logging::Initialize()
             spdlog::info("{} v{} loaded.", sFixName, sFixVersion);
             spdlog::info("ASI plugin location: {}", (sExePath / sFixPath / (sFixName + ".asi")).string());
             spdlog::info("----------");
-            spdlog::info("Log file: {}", (sExePath / "logs" / sLogFile).string());
+            spdlog::info("Log file: {}", g_Logging.sLogFile.string());
             if (std::filesystem::path pOldLogFile = sExePath / "logs" / (sFixName + ".log"); std::filesystem::exists(pOldLogFile))
             {
                 spdlog::warn("Found an outdated log file from a previous version of MGSHDFix. Removing: {}", pOldLogFile.string());
-                std::filesystem::remove(pOldLogFile);
+                //std::filesystem::remove(pOldLogFile);
```
Comment (ShizCalev) [inline src/resources/logging.cpp]:
```suggestion
                std::filesystem::remove(pOldLogFile);
```

**Review by ShizCalev — COMMENTED** [review]
marking these so i don't leave them in by accident
